global:
  resolve_timeout: 1m

route:
  receiver: 'webhook_receiver'
  group_wait: 0s 
  group_interval: 1m
  repeat_interval: 30m

receivers:
  - name: 'webhook_receiver'
    webhook_configs:
      - url: 'http://192.168.56.1:5000/alerts' # this is self hosted test python script for webhook receive
        send_resolved: true