Vagrant.configure("2") do |config|
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/bookworm64"
    debian.vm.hostname = "debian-node"
    debian.vm.network "private_network", ip: "192.168.56.4"

    debian.vm.provider "virtualbox" do |vb|
      vb.name   = "debian-node"
      vb.cpus   = 2
      vb.memory = 2048
    end
  end
end
